name: Profile Readme Action

on:
  schedule:
    - cron: "*/1 * * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Update GitHub Profile README
        uses: theboi/github-update-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          header: "Hey, I'm Jedidiah Amaraegbu! 👋"
          subhead: "Currently a student at the University of Nigeria Nsukka, passionate about using all-things-tech to bring ideas to life."
          footer: "**Learn more about me at [amjedidiah.me](http://amjedidiah.me)!**"
